### ISSUE TITLE
Cannot delete product images programmatically in Magento 2.1.7

### ISSUE THREAD

**Issue by JacobDrummond** [DIE-KAVALLERIE/magento2-product-image-fix#1]
### Environment
* Ubuntu 14.04 LTS (GNU/Linux 3.13.0-117-generic x86_64)
* nginx/1.4.6 (Ubuntu)
* MySQL 5.6.34-log
* PHP 5.6.16
* Magento CE 2.1.7
* DieKavallerie_ProductImageFix at commit [6e64846425220faaec79f373ab5f7635a13a17ed](/DIE-KAVALLERIE/magento2-product-image-fix/tree/6e64846425220faaec79f373ab5f7635a13a17ed/)

### Replication steps
Create a console command with the following lines (replace `ProductRepository` with a real instance):

```php
$product = \Magento\Catalog\Model\ProductRepository->get('XYZ');
$product->setMediaGalleryEntries([]);
$this->productRepository->save($product);
```

### Expected result
* Media gallery entries removed from database
* `/media/` files removed

### Actual result
* DB entries and files are intact

**Comment by eduard-kistner** [comment]
Thanks for submitting the BUG report.
Sadly this seems not to be an issue directly related to our module but an general Magento issue ?!

IMO the main problem is that the current implementation is somewhere ignoring possible use cases.
So when you set an empty media gallery that does not mean that the real gallery data is touched.
Its not as the product model is just holding references of the image objects.

So yes, you set nothing but that does not unset something ;)

If you want your images removed you must declare them to be removed, like:
```php
$productRepo      = $this->getObjectManager()->get('Magento\Catalog\Model\ProductRepository');
$product          = $productRepo->get('XYZ');
$galleryProcessor = $this->getObjectManager()->get('Magento\Catalog\Model\Product\Gallery\Processor');

foreach ($product->getMediaGalleryEntries() as $media) {
    $galleryProcessor->removeImage($product, $media['file']);
}

$productRepo->save($product);
```

**Comment by JacobDrummond** [comment]
@eduard-kistner,

Thanks for making this module :) The [addImageToMediaGallery exception bug](/magento/magento2/issues/6803) was driving us crazy before you fixed it.

However, `$product->setMediaGalleryEntries([])` works for me when `DieKavallerie_ProductImageFix` is disabled. So it appears to be this module breaking something.

`$galleryProcessor->removeImage()` is a great workaround for now, though. Thank you for taking the time to document it.

**Comment by eduard-kistner** [comment]
@JacobDrummond 

Great to here that the module is usefull for others :)

As i have tried  `$product->setMediaGalleryEntries([])` without success ( also with removed Module ) that seemed for me as an general problem.
But to admit we havent tried it in an blank Magento 2 install Oo

So great if the "workaround" works for you.

EDIT:
Clarified that we also have checked with removed module.
